[package]
name = "rusty-fractals"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = "^0.15"
num = "0.4.0"
image = "0.24.5"
random_color = "0.6.1"
colourado = "0.2.0"
